{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"churn\",\"churn - unpivot groups\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6ad6142f-5074-4c11-abbe-71f62baf3097",
        "fromColumn": "customerID",
        "fromTable": "churn - unpivot groups",
        "toColumn": "customerID",
        "toTable": "churn"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "churn",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be396566-8e30-460d-bc48-88488f850596",
            "sourceColumn": "customerID",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f854483-4214-42c6-a735-516670d51e52",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "SeniorCitizen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e4e5c3a-7609-4daf-9d39-a6f062f0e7f9",
            "sourceColumn": "SeniorCitizen",
            "summarizeBy": "none"
          },
          {
            "name": "Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9493de35-6736-4db2-932c-a4c0aa8e7fea",
            "sourceColumn": "Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Dependents",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f31c843d-9b52-477f-9b3c-c542069f5357",
            "sourceColumn": "Dependents",
            "summarizeBy": "none"
          },
          {
            "name": "tenure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42de421a-98f9-49a0-a36e-ac35b180b40f",
            "sourceColumn": "tenure",
            "summarizeBy": "none"
          },
          {
            "name": "PhoneService",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e763f2b9-2e2d-4f7f-84ab-013f9afec155",
            "sourceColumn": "PhoneService",
            "summarizeBy": "none"
          },
          {
            "name": "MultipleLines",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5c379c1-0a9d-4248-8633-456639df854a",
            "sourceColumn": "MultipleLines",
            "summarizeBy": "none"
          },
          {
            "name": "InternetService",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2de556fd-c08c-4559-b698-55c93b041464",
            "sourceColumn": "InternetService",
            "summarizeBy": "none"
          },
          {
            "name": "OnlineSecurity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1f93c6e-4497-49e4-a62d-a1a6d94549ec",
            "sourceColumn": "OnlineSecurity",
            "summarizeBy": "none"
          },
          {
            "name": "OnlineBackup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56c78549-daf7-4097-8abb-b02fa55d3059",
            "sourceColumn": "OnlineBackup",
            "summarizeBy": "none"
          },
          {
            "name": "DeviceProtection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54cc6931-58f8-44c5-9467-58420ed92041",
            "sourceColumn": "DeviceProtection",
            "summarizeBy": "none"
          },
          {
            "name": "TechSupport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afb62e72-8643-40dd-99ca-296a6cffe360",
            "sourceColumn": "TechSupport",
            "summarizeBy": "none"
          },
          {
            "name": "StreamingTV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e010c64-dfe9-4fda-b2c6-40e695dd3645",
            "sourceColumn": "StreamingTV",
            "summarizeBy": "none"
          },
          {
            "name": "StreamingMovies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33b2f26a-5af9-4e62-883b-bc462d6ba52a",
            "sourceColumn": "StreamingMovies",
            "summarizeBy": "none"
          },
          {
            "name": "Contract",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08e80cfa-8287-4d4b-ab32-4c6be8318f95",
            "sourceColumn": "Contract",
            "summarizeBy": "none"
          },
          {
            "name": "PaperlessBilling",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"churn\",\"TableItemName\":\"PaperlessBilling (Gruppen)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "141beeb8-2ee1-43df-b0b6-663886b119fe",
            "sourceColumn": "PaperlessBilling",
            "summarizeBy": "none"
          },
          {
            "name": "PaymentMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb4dde8a-e886-4361-813f-9ec3060bc92d",
            "sourceColumn": "PaymentMethod",
            "summarizeBy": "none"
          },
          {
            "name": "MonthlyCharges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "31d0f90e-e8bd-4255-964b-5dd3cf7da25d",
            "sourceColumn": "MonthlyCharges",
            "summarizeBy": "none"
          },
          {
            "name": "TotalCharges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "210814c8-9edd-4a01-b58a-44c5c6789dac",
            "sourceColumn": "TotalCharges",
            "summarizeBy": "none"
          },
          {
            "name": "numAdminTickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70c6c1b6-2a9f-45f4-9985-7c12c56a6c3c",
            "sourceColumn": "numAdminTickets",
            "summarizeBy": "none"
          },
          {
            "name": "numTechTickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f820949-0300-4e08-8038-e8ff2b58bd4e",
            "sourceColumn": "numTechTickets",
            "summarizeBy": "none"
          },
          {
            "name": "Churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19bc159f-bfb4-460d-805a-0cae519a1293",
            "sourceColumn": "Churn",
            "summarizeBy": "none"
          },
          {
            "name": "PaperlessBilling (Gruppen)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"c\",\"Entity\":\"churn\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"PaperlessBilling\"}}],\"GroupItems\":[{\"DisplayName\":\"(Leer)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Yes\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"PaperlessBilling\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Yes'\"}}]]}}},{\"DisplayName\":\"Sonstige\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('churn'[PaperlessBilling]),",
              "  \"(Leer)\",",
              "  'churn'[PaperlessBilling] IN {\"Yes\"},",
              "  \"Yes\",",
              "  \"Sonstige\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "churn"
                          }
                        },
                        "Property": "PaperlessBilling"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "334e94fb-c986-4538-9cac-a321a18ee197",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Loyalty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adc3c4ef-f5a2-41d6-b341-a389dba2710d",
            "sourceColumn": "Loyalty",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3f141df4-a35c-4907-a792-bf0da62cafff",
        "measures": [
          {
            "name": "Count of Churn for Yes",
            "expression": [
              "",
              "CALCULATE(COUNTA('churn'[Churn]), 'churn'[Churn] IN { \"Yes\" })"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "8c28c41c-4977-449d-a93b-5dfac5fcf1fa"
          },
          {
            "name": "Count of MultipleLines for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[MultipleLines]),",
              "\t'churn'[MultipleLines] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "55b7a704-4617-4952-9851-eedbdb7155ee"
          },
          {
            "name": "Count of PhoneService for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[PhoneService]),",
              "\t'churn'[PhoneService] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "9416ecaa-08d4-4e30-bb3d-360972b6bb2c"
          },
          {
            "name": "Count of OnlineSecurity for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[OnlineSecurity]),",
              "\t'churn'[OnlineSecurity] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "6ace44de-e6a2-4a94-bfa0-8e09798d9d3a"
          },
          {
            "name": "Count of OnlineBackup for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[OnlineBackup]),",
              "\t'churn'[OnlineBackup] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "8292889f-bb9e-47b2-b5c6-a55bb55eddff"
          },
          {
            "name": "Count of DeviceProtection for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[DeviceProtection]),",
              "\t'churn'[DeviceProtection] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "d23d0a8a-d2b8-422d-af68-a929866693d2"
          },
          {
            "name": "Count of TechSupport for Yes",
            "expression": [
              "",
              "CALCULATE(COUNTA('churn'[TechSupport]), 'churn'[TechSupport] IN { \"Yes\" })"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "d839666e-f435-4915-ab1f-137137206d78"
          },
          {
            "name": "Count of StreamingMovies for Yes",
            "expression": [
              "",
              "CALCULATE(",
              "\tCOUNTA('churn'[StreamingMovies]),",
              "\t'churn'[StreamingMovies] IN { \"Yes\" }",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "9b49a6e7-29e0-4319-af95-ea0967e6c427"
          },
          {
            "name": "Count of StreamingTV for Yes",
            "expression": [
              "",
              "CALCULATE(COUNTA('churn'[StreamingTV]), 'churn'[StreamingTV] IN { \"Yes\" })"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "FilteredMeasure",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "5ac88fb3-d4dd-4ddd-a8b8-210ada4297c0"
          },
          {
            "name": "SeniorCitizen in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[SeniorCitizen]), churn[SeniorCitizen]=1, churn[Churn]= \"Yes\"), CALCULATE(COUNT(churn[SeniorCitizen]), churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "171c1071-633d-40fa-9dff-84c9641833c3"
          },
          {
            "name": "Partner in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[Partner]), churn[Partner]=\"Yes\", churn[Churn]= \"Yes\"), CALCULATE(COUNT(churn[Partner]), churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5fcc8a63-4a1b-4619-a457-be1660a80072"
          },
          {
            "name": "Dependents in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[Dependents]), churn[Dependents]=\"Yes\", churn[Churn]= \"Yes\"), CALCULATE(COUNT(churn[Dependents]), churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "1f7155e9-f45c-4ef6-b28d-5cee890846e3"
          },
          {
            "name": "Multiple Lines yes in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[MultipleLines]), churn[MultipleLines]=\"Yes\", churn[Churn]= \"Yes\"), CALCULATE(COUNT(churn[MultipleLines]), churn[Churn]=\"Yes\", churn[MultipleLines] <> \"No phone service\"),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5f781b43-7eb1-4f31-957c-9315d5e07ed1"
          },
          {
            "name": "Multiple lines no in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[MultipleLines]), churn[MultipleLines]=\"No\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[MultipleLines]),churn[Churn]=\"Yes\", churn[MultipleLines] <> \"No phone service\"),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "837aa1ab-bc6a-48b6-b3ba-65573bd096a9"
          },
          {
            "name": "Online Sec. in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[OnlineSecurity]), churn[OnlineSecurity]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[OnlineSecurity]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "867ea71a-f340-481b-9ca9-63f5ba4ddadd"
          },
          {
            "name": "Online Bacup in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[OnlineBackup]), churn[OnlineBackup]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[OnlineBackup]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "75c9350f-6247-4511-9efe-1dac509c5c73"
          },
          {
            "name": "Streaming TV in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[StreamingTV]), churn[StreamingTV]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[StreamingTV]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "9b03a435-dc22-49c4-8242-4918d007f5e6"
          },
          {
            "name": "Streaming Movies in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[StreamingMovies]), churn[StreamingMovies]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[StreamingMovies]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "79081de8-4f02-4d00-b290-1fcd8a51a0cf"
          },
          {
            "name": "Device protection in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[DeviceProtection]), churn[DeviceProtection]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[DeviceProtection]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "3ed8fd03-66e4-4f9c-98f0-fe3c19c7046e"
          },
          {
            "name": "Tech Support in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[TechSupport]), churn[TechSupport]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[TechSupport]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "bfc8f7b7-20b8-4c33-a25c-9ab9e84574dd"
          },
          {
            "name": "Phone Service in %",
            "expression": "DIVIDE(CALCULATE(COUNT(churn[PhoneService]), churn[PhoneService]=\"Yes\", churn[Churn]=\"Yes\"),CALCULATE(COUNT(churn[PhoneService]),churn[Churn]=\"Yes\"),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ad9c99bc-2297-4211-b317-baedf3faa9f5"
          },
          {
            "name": "churn rate %",
            "expression": [
              "DIVIDE (CALCULATE(COUNT(churn[Churn]), churn[Churn] = \"yes\" ),CALCULATE ( COUNT (churn[Churn]), ALLSELECTED (churn[Churn] ) )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1071d857-c74d-435e-babf-0af80ba985c6"
          }
        ],
        "partitions": [
          {
            "name": "churn-62bfc29c-c8e4-4672-9633-e854d0fa9a51",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\GDIC\\Documents\\BSc BA - Int. Mgmt\\Semester 6\\Business Interlligence\\BI Assignment\\churn.csv\"),[Delimiter=\",\", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customerID\", type text}, {\"gender\", type text}, {\"SeniorCitizen\", Int64.Type}, {\"Partner\", type text}, {\"Dependents\", type text}, {\"tenure\", Int64.Type}, {\"PhoneService\", type text}, {\"MultipleLines\", type text}, {\"InternetService\", type text}, {\"OnlineSecurity\", type text}, {\"OnlineBackup\", type text}, {\"DeviceProtection\", type text}, {\"TechSupport\", type text}, {\"StreamingTV\", type text}, {\"StreamingMovies\", type text}, {\"Contract\", type text}, {\"PaperlessBilling\", type text}, {\"PaymentMethod\", type text}, {\"MonthlyCharges\", type number}, {\"TotalCharges\", type number}, {\"numAdminTickets\", Int64.Type}, {\"numTechTickets\", Int64.Type}, {\"Churn\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Risk category\", each if [tenure] < 24 then \"Risk 1\" else if [tenure] < 48 then \"Risk 2\" else \"Risk 3\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"Loyalty\", each if [tenure] < 12 then \"< 1 year\" else if [tenure] < 24 then \"< 2 years\" else if [tenure] < 36 then \"< 3 years\" else if [tenure] < 48 then \"< 4 years\" else if [tenure] < 60 then \"< 5 years\" else \"< 6 years\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column1\",{\"Risk category\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_d9b7efed-fa11-4557-bae3-304004ebf6d4",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a0078b9-97d9-449c-9754-85d176541437",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6c8d42b2-daa3-40e7-b4fb-ec2f0b2e2384",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "334d49bb-4be4-4065-9c9b-d045b4f9a92a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8705713c-718a-4e22-9eaf-e876ae11a402",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ae53679e-3c88-4a76-9aa1-e0b5112cf818",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "07b7ba5e-3e0c-4845-a527-47274e6ca9e8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7639a0f6-1906-4dd7-be8d-fb93e4618d08",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "df04442e-b51e-4083-8deb-8b9cc0dd7b85",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8dfc3b77-0518-473a-825e-ea400a9ab7c8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "704c4f46-e864-492f-a22b-d3c2a97d47ab",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3ae5eef9-d886-4447-97bf-311ec84aad0f",
                "ordinal": 3
              }
            ],
            "lineageTag": "da3f3d4d-90d5-4212-bcb2-d613e6d2086d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "550fed3c-49a3-4e0f-856f-a75b128beac8",
        "partitions": [
          {
            "name": "DateTableTemplate_d9b7efed-fa11-4557-bae3-304004ebf6d4-9991c143-eaa8-42f6-9549-832acbf7051e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "churn - unpivot groups",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e7a9c8a-dee5-4a66-8867-830a42f1d285",
            "sourceColumn": "customerID",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "433ff1a1-c3c2-4595-b686-19fc3b4360c9",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "SeniorCitizen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c886f49f-ddb3-4e65-b7f1-c0606ddd021c",
            "sourceColumn": "SeniorCitizen",
            "summarizeBy": "sum"
          },
          {
            "name": "Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62e9e4b0-5277-401e-a6bb-bfeccca7e097",
            "sourceColumn": "Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Dependents",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0231ac1c-a418-49e2-9eba-c3791ea4ec08",
            "sourceColumn": "Dependents",
            "summarizeBy": "none"
          },
          {
            "name": "tenure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "053936d7-f843-433d-92cf-aa4d2d612fe8",
            "sourceColumn": "tenure",
            "summarizeBy": "sum"
          },
          {
            "name": "Contract",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f49d5a4e-e906-4367-8a62-f3b70779485a",
            "sourceColumn": "Contract",
            "summarizeBy": "none"
          },
          {
            "name": "PaperlessBilling",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "603ede44-a950-4974-89a4-38e05d337d35",
            "sourceColumn": "PaperlessBilling",
            "summarizeBy": "none"
          },
          {
            "name": "PaymentMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f74021f-1faf-44d4-be71-c551a31b3c6e",
            "sourceColumn": "PaymentMethod",
            "summarizeBy": "none"
          },
          {
            "name": "MonthlyCharges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "622b8b7f-8e2f-41f8-a44f-6763e77f5d0d",
            "sourceColumn": "MonthlyCharges",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCharges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63fe34aa-c10a-42d9-a13a-55307da6e265",
            "sourceColumn": "TotalCharges",
            "summarizeBy": "sum"
          },
          {
            "name": "numAdminTickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "261cae74-52b0-495e-afcd-0ab99c3158c1",
            "sourceColumn": "numAdminTickets",
            "summarizeBy": "sum"
          },
          {
            "name": "numTechTickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7305b6cd-6ec5-429b-b840-1c792b30bbd5",
            "sourceColumn": "numTechTickets",
            "summarizeBy": "sum"
          },
          {
            "name": "Churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29f8daa8-aa19-4c33-9842-309f2df172ca",
            "sourceColumn": "Churn",
            "summarizeBy": "none"
          },
          {
            "name": "Risk category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "658bafaf-8723-4388-a19b-b45d80b6acee",
            "sourceColumn": "Risk category",
            "summarizeBy": "none"
          },
          {
            "name": "Loyalty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7c2d4a5-113a-4f00-9272-3a52b4c71a23",
            "sourceColumn": "Loyalty",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d1c996b-66dd-4b22-8ec6-c575923001e1",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b015d4a-6351-4fc4-a3ad-6091fa6cb79a",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "37b73c40-2983-4b59-8eb8-0f2dc3ebc8c7",
        "partitions": [
          {
            "name": "churn - unpivot groups-74e8f43e-10ae-4f79-8341-26933b43ce72",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\GDIC\\Documents\\BSc BA - Int. Mgmt\\Semester 6\\Business Interlligence\\BI Assignment\\churn.csv\"),[Delimiter=\",\", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customerID\", type text}, {\"gender\", type text}, {\"SeniorCitizen\", Int64.Type}, {\"Partner\", type text}, {\"Dependents\", type text}, {\"tenure\", Int64.Type}, {\"PhoneService\", type text}, {\"MultipleLines\", type text}, {\"InternetService\", type text}, {\"OnlineSecurity\", type text}, {\"OnlineBackup\", type text}, {\"DeviceProtection\", type text}, {\"TechSupport\", type text}, {\"StreamingTV\", type text}, {\"StreamingMovies\", type text}, {\"Contract\", type text}, {\"PaperlessBilling\", type text}, {\"PaymentMethod\", type text}, {\"MonthlyCharges\", type number}, {\"TotalCharges\", type number}, {\"numAdminTickets\", Int64.Type}, {\"numTechTickets\", Int64.Type}, {\"Churn\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Risk category\", each if [tenure] < 24 then \"Risk 1\" else if [tenure] < 48 then \"Risk 2\" else \"Risk 3\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"Loyalty\", each if [tenure] < 6 then \"< 6 months\" else if [tenure] < 12 then \"< 12 months\" else if [tenure] < 18 then \"< 18 months\" else if [tenure] < 24 then \"< 2 years\" else if [tenure] < 36 then \"< 3 years\" else if [tenure] < 48 then \"< 4 years\" else \"4 years +\"),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Added Conditional Column1\", {\"customerID\", \"gender\", \"SeniorCitizen\", \"Partner\", \"Dependents\", \"tenure\", \"Contract\", \"PaperlessBilling\", \"PaymentMethod\", \"MonthlyCharges\", \"TotalCharges\", \"numAdminTickets\", \"numTechTickets\", \"Churn\", \"Risk category\", \"Loyalty\"}, \"Attribute\", \"Value\")",
                "in",
                "    #\"Unpivoted Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}